### ISSUE TITLE
Mesh refinement broken

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#1232]
Mesh refinement cases a runtime error when assembling matrices:
```
import dolfinx
import ufl
from dolfinx.mesh import refine
from mpi4py import MPI

mesh = dolfinx.UnitCubeMesh(MPI.COMM_WORLD, 3, 3, 3)
mesh.topology.create_entities(mesh.topology.dim - 2)
mesh = refine(mesh, redistribute=True)
V = dolfinx.FunctionSpace(mesh, ("CG", 1))

# Define variational problem
u = ufl.TrialFunction(V)
v = ufl.TestFunction(V)
a = ufl.inner(ufl.grad(u), ufl.grad(v)) * ufl.dx

# Assemble rhs, RHS and apply lifting
A_org = dolfinx.fem.assemble_matrix(a)
A_org.assemble()
```
Causing
```
Traceback (most recent call last):
  File "debug_ref.py", line 19, in <module>
    A_org = dolfinx.fem.assemble_matrix(a)
  File "/usr/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/shared/dolfinx/python/dolfinx/fem/assemble.py", line 209, in assemble_matrix
    A = cpp.fem.create_matrix(_create_cpp_form(a))
  File "/home/shared/dolfinx/python/dolfinx/fem/assemble.py", line 27, in _create_cpp_form
    return Form(form)._cpp_object
  File "/home/shared/dolfinx/python/dolfinx/fem/form.py", line 69, in __init__
    self._cpp_object = cpp.fem.create_form(ffi.cast("uintptr_t", ufc_form),
RuntimeError: Incompatible mesh
```

**Comment by chrisrichardson** [comment]
Could be related to some recent changes I made.

**Comment by chrisrichardson** [comment]
This only affects the Python layer due to incorrect copying of "ufl_domain" from parent mesh. Addressed in branch `chris/fix-python-refinement`

**Comment by chrisrichardson** [comment]
https://github.com/FEniCS/dolfinx/tree/chris/fix-python-refinement
