### ISSUE TITLE
RectangleMesh ignores z-component of Points

### ISSUE THREAD

**Issue by BenjaminRodenberg** [FEniCS/dolfinx#1872]
I'm currently migrating a FEniCS-based code to dolfinx. In my FEniCS code I used the following for creating a rectangle in a 2D domain:
```
from fenics import Point, RectangleMesh

p0 = Point(0, 0)
p1 = Point(1, 1)
nx, ny = 10, 10
mesh = RectangleMesh(p0, p1, nx, ny, diagonal="left")
```
I translated this to
```
from dolfinx import Point, RectangleMesh
from mpi4py import MPI

p0 = (0, 0, 0)
p1 = (1, 1, 0)
nx, ny = 10, 10
mesh = RectangleMesh(MPI.COMM_WORLD, [p0, p1], [nx, ny], diagonal="left")
```
Two things I found irritating:

## 1. Why do I have to provide a z-component, even if the mesh is in 2D?

If I only provide two components, I get an error:
```
>>> m = dolfinx.RectangleMesh(MPI.COMM_WORLD, [(0,0), (1,1)], [10,10], diagonal="left")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/benjamin/.local/lib/python3.8/site-packages/dolfinx/generation.py", line 76, in RectangleMesh
    mesh = cpp.generation.create_rectangle_mesh(comm, points, n, cell_type, ghost_mode, partitioner, diagonal)
TypeError: create_rectangle_mesh(): incompatible function arguments. The following argument types are supported:
    1. (comm: MPICommWrapper, p: List[List[float[3]][2]], n: List[int[2]], celltype: dolfinx.cpp.mesh.CellType, ghost_mode: dolfinx.cpp.mesh.GhostMode, partitioner: Callable[[MPICommWrapper, int, int, dolfinx.cpp.graph.AdjacencyList_int64, dolfinx.cpp.mesh.GhostMode], dolfinx.cpp.graph.AdjacencyList_int32], diagonal: str) -> dolfinx.cpp.mesh.Mesh

Invoked with: <mpi4py.MPI.Intracomm object at 0x7fb6a82c2f90>, [(0, 0), (1, 1)], [10, 10], <CellType.triangle: 3>, <GhostMode.shared_facet: 1>, <built-in method partition_cells_graph of PyCapsule object at 0x7fb69fdb96f0>, 'left'
```

## 2. I tried to add a non-zero z-component and found out that it is just ignored.

Is this a bug?
```
>>> m = dolfinx.RectangleMesh(MPI.COMM_WORLD, [(0,0,1), (1,1,2)], [10,10], diagonal="left")
>>> m.geometry.x
array([[1. , 0.9, 0. ],
       [0.9, 1. , 0. ],
       [1. , 1. , 0. ],
       [0.9, 0.9, 0. ],
       [1. , 0.8, 0. ],
       [0.8, 1. , 0. ],
       [0.9, 0.8, 0. ],
       ...
```
I would expect some kind of warning here.

**Comment by jorgensd** [comment]
The 2D built-in meshes `UnitSquareMesh` and `RectangleMesh` will always have a zero z-component.

The reason for the `geometry.x` being 3D is that is improves assembly as one has fixed-with geometry input.
To verify that the geometry has the correct dimensionality, you can call `print(mesh.geometry.dim)`, which will return 2 in your case, as shown in the code below (adapted to work with the main branch):
```python
from dolfinx.generation import DiagonalType, RectangleMesh
from mpi4py import MPI

p0 = (0, 0, 0)
p1 = (1, 1, 0)
nx, ny = 2, 2
mesh = RectangleMesh(MPI.COMM_WORLD, [p0, p1], [nx, ny], diagonal=DiagonalType.left)
print(mesh.geometry.dim,"\n", mesh.geometry.x)
```
```bash
2 
 [[0.  0.  0. ]
 [0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.5 0.5 0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [1.  0.5 0. ]
 [0.5 1.  0. ]
 [1.  1.  0. ]]
```

**Comment by jhale** [comment]
Agree with @jorgensd answer. Nevertheless, this interface could be smoothed a bit from the Python side? The third coordinate seems like an implementation detail that the user shouldn't really have to concern themselves with.
