### ISSUE TITLE
A Singularity image for dolfinx

### ISSUE THREAD

**Issue by bhaveshshrimali** [FEniCS/dolfinx#2066]
Hi everyone, 

I am trying to install dolfinx on our University cluster which uses singularity. However, pulling a recent nightly release from dockerhub doesn't run as expected (it doesn't find dolfinx). Does anyone here have experience building singularity images off of the base docker image for dolfinx (recent releases).  

```terminal
singularity pull --name dolfinx.sif docker://dolfinx/dolfinx
[bshrima2@golubh1]$ singularity shell dolfinx.sif
WARNING: seccomp requested but not enabled, seccomp library is missing or too old
Singularity dolfinx.sif:/projects/meca/bshrima2> python3 -c "import dolfinx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'dolfinx'
Singularity dolfinx.sif:/projects/meca/bshrima2>

``` 

Everything is fine on the docker side, so I don't suspect there are any issues per-se with the image but any help would be appreciated. In the meantime I have asked the folks at the help desk of our cluster too. 

Thanks,
Bhavesh

**Comment by bhaveshshrimali** [comment]
Hmm.. weird I do see the dependencies in place but not dolfinx.. 
```
Singularity dolfinx.sif:/projects/meca/bshrima2> which pip3
/usr/bin/pip3
Singularity dolfinx.sif:/projects/meca/bshrima2> pip3 list
Package                       Version
----------------------------- -------------
alabaster                     0.7.12
asttokens                     2.0.5
attrs                         21.4.0
Babel                         2.9.1
backcall                      0.2.0
certifi                       2021.10.8
cffi                          1.15.0
charset-normalizer            2.0.12
cppimport                     21.3.7
decorator                     4.4.2
docutils                      0.17.1
dolfiny                       0.1
execnet                       1.9.0
executing                     0.8.3
fenics-basix                  0.3.1.dev0
fenics-ffcx                   0.3.1.dev0
fenics-ufl                    2021.2.0.dev0
flake8                        4.0.1
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.11.2
iniconfig                     1.1.1
ipython                       8.1.1
ipython-genutils              0.2.0
isort                         5.10.1
jedi                          0.18.1
Jinja2                        3.0.3
jsonschema                    4.4.0
jupyter-core                  4.9.2
jupytext                      1.13.7
llvmlite                      0.38.0
Mako                          1.1.6
markdown-it-py                1.1.0
MarkupSafe                    2.1.0
matplotlib-inline             0.1.3
mccabe                        0.6.1
mdit-py-plugins               0.3.0
mpi4py                        3.1.3
myst-parser                   0.17.0
nbformat                      5.1.3
numba                         0.55.1
numpy                         1.21.5
olefile                       0.46
packaging                     21.3
parso                         0.8.3
petsc4py                      3.16.4
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.1.2
pip                           20.3.4
pluggy                        1.0.0
prompt-toolkit                3.0.28
ptyprocess                    0.7.0
pure-eval                     0.2.2
py                            1.11.0
pybind11                      2.9.1
```

```
Singularity dolfinx.sif:/projects/meca/bshrima2> python3 -c "import dolfinx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'dolfinx'
Singularity dolfinx.sif:/projects/meca/bshrima2>

```

**Comment by bhaveshshrimali** [comment]
And if I simply search for `dolfinx` it seems it is there...
```
Singularity dolfinx.sif:/usr> find /usr/ -type d -name "dolfinx"
/usr/local/dolfinx-complex/include/dolfinx
/usr/local/dolfinx-complex/lib/cmake/dolfinx
/usr/local/dolfinx-complex/lib/dolfinx
/usr/local/dolfinx-complex/lib/python3.8/dist-packages/dolfinx
/usr/local/dolfinx-complex/share/dolfinx
/usr/local/dolfinx-real/include/dolfinx
/usr/local/dolfinx-real/lib/cmake/dolfinx
/usr/local/dolfinx-real/lib/dolfinx
/usr/local/dolfinx-real/lib/python3.8/dist-packages/dolfinx
/usr/local/dolfinx-real/share/dolfinx
```

Edit: Somehow the cluster loaded `python/3` module by default and as a result my path was getting overwritten. I checked by printing `sys.path` and indeed there was no dolfinx. Unloading the system `python/3` and checking again, I think things are OK...

```
Python 3.9.7 (default, Sep 10 2021, 14:59:43)
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/local/dolfinx-real/lib/python3.8/dist-packages', '/usr/local/lib', '/projects/meca/bshrima2/dolfinxPractice', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/home/bshrima2/.local/lib/python3.9/site-packages', '/usr/local/lib/python3.9/dist-packages', '/usr/lib/python3/dist-packages']
>>> import dolfinx
>>>
```


Thanks

**Comment by jhale** [comment]
Glad you got it working. I think there are various options in Singularity to isolate containers above the defaults, which are a lot more permissive than other container engines (Docker, Podman etc.).
