### ISSUE TITLE
broken complex mode in docker image

### ISSUE THREAD

**Issue by francesco-ballarin** [FEniCS/dolfinx#2201]
```
$ docker run -it --rm dolfinx/dolfinx
root@0693c5ef81e6:~# . /usr/local/bin/dolfinx-complex-mode
root@0693c5ef81e6:~# python3 -c 'import dolfinx.cpp'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/dolfinx-complex/lib/python3.8/dist-packages/dolfinx/__init__.py", line 33, in <module>
    from dolfinx import common
  File "/usr/local/dolfinx-complex/lib/python3.8/dist-packages/dolfinx/common.py", line 10, in <module>
    from dolfinx import cpp as _cpp
ImportError: /usr/local/dolfinx-complex/lib/python3.8/dist-packages/dolfinx/cpp.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN7dolfinx3fem5petsc18create_matrix_nestERKSt6vectorIS2_IPKNS0_4FormIdEESaIS6_EESaIS8_EERKS2_IS2_INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISI_EESaISK_EE
root@0693c5ef81e6:~# 
```

**Comment by jhale** [comment]
Fixed in PR #2200

**Comment by francesco-ballarin** [comment]
The actual fix will be in #2211

**Comment by francesco-ballarin** [comment]
Neither PR fix the issue

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/__w/multiphenicsx/multiphenicsx/multiphenicsx/cpp/__init__.py", line 12, in <module>
    from multiphenicsx.cpp.compile_code import compile_code
  File "/__w/multiphenicsx/multiphenicsx/multiphenicsx/cpp/compile_code.py", line 15, in <module>
    import dolfinx.jit
  File "/usr/local/dolfinx-complex/lib/python3.10/dist-packages/dolfinx/__init__.py", line 29, in <module>
    from dolfinx import common
  File "/usr/local/dolfinx-complex/lib/python3.10/dist-packages/dolfinx/common.py", line 10, in <module>
    from dolfinx import cpp as _cpp
ImportError: /usr/local/dolfinx-complex/lib/python3.10/dist-packages/dolfinx/cpp.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN7dolfinx3fem5petsc18create_matrix_nestERKSt6vectorIS2_IPKNS0_4FormIdEESaIS6_EESaIS8_EERKS2_IS2_INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISI_EESaISK_EE
```

**Comment by garth-wells** [comment]
Hmm, why isn't the CI picking this up?
