### ISSUE TITLE
Importing dolfinx crashing in python 3.10

### ISSUE THREAD

**Issue by ashutoshmaurya1122** [FEniCS/dolfinx#2258]
I have installed Fenicsx using Ubuntu PPA (Ubuntu 22.04). However if i try to import dolfinx it crashes with following Traceback

` import dolfinx`
`Traceback (most recent call last):'`
  `File "<stdin>", line 1, in <module>`
  `File "/usr/lib/petsc/lib/python3/dist-packages/dolfinx/__init__.py", line 35, in <module>`
   ` from dolfinx import fem, geometry, graph, io, jit, la, log, mesh, nls, plot`
  `File "/usr/lib/petsc/lib/python3/dist-packages/dolfinx/fem/__init__.py", line 11, in <module>`
    `from dolfinx.fem import petsc`
  `File "/usr/lib/petsc/lib/python3/dist-packages/dolfinx/fem/petsc.py", line 33, in <module>`
   ` from dolfinx.fem.function import Function as _Function`
  `File "/usr/lib/petsc/lib/python3/dist-packages/dolfinx/fem/function.py", line 30, in <module>`
   ` class Constant(ufl.Constant):`
`TypeError: function() argument 'code' must be code, not str`

**Comment by garth-wells** [comment]
Any ideas @drew-parsons?

**Comment by drew-parsons** [comment]
I've confirmed dolfinx is importing successfully in python3.10 in fresh installation of Ubuntu jammy (22.04), with (dolfinx 0.4) or without (dolfinx 0.3) the PPA.  It's also working with the Debian (unstable) build.

It looks like a mismatch with the ufl API, which suggests to me the installation is not fully updated (doesn't have the new ufl). Make sure you're updated with
```
sudo apt-get update
sudo apt-get upgrade
```
If you've upgraded from an older Ubuntu release then some of the new libraries might be held back.  In that case complete the full upgrade with
```
sudo apt-get dist-upgrade
``` 
(this is needed for example if you had the standard jammy build of dolfinx 0.3.0 already installed before adding the PPA to access dolfinx 0.4)

**Comment by ashutoshmaurya1122** [comment]
Finally fixed, the issue was with fenics package. If you have installed fenics and try to install fenicsx , dolfinx will use fenics-ufl-2019.1.0 which was causing crash.
