### ISSUE TITLE
Manifold meshes from XDMF broken

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#2389]
Broken by PR #2301 
Reported at: https://fenicsproject.discourse.group/t/triangle-elements-in-3d-broken-in-dolfinx/9426
MWE:
XDMFFile:
```xdmf
<Xdmf Version="3.0">
  <Domain>
    <Grid Name="Grid">
      <Geometry GeometryType="XYZ">
        <DataItem DataType="Float" Dimensions="3 2" Format="XML" Precision="8">
          0.0 0.0 0.0
          1.0 0.0 0.0
          0.0 1.0 0.0
        </DataItem>
      </Geometry>
      <Topology NodesPerElement="3" NumberOfElements="1" TopologyType="triangle">
        <DataItem DataType="Int" Dimensions="1 3" Format="XML" Precision="4">
          0 1 2
        </DataItem>
      </Topology>
    </Grid>
  </Domain>
</Xdmf>
```
and code 
```python
#!/usr/bin/env python3
from mpi4py import MPI
from dolfinx import fem, io
import ufl

comm = MPI.COMM_WORLD

meshname = 'mesh.xdmf'

with io.XDMFFile(comm, meshname, 'r', encoding=io.XDMFFile.Encoding.ASCII) as infile:

    mesh = infile.read_mesh(name="Grid")

V_s = fem.FunctionSpace(mesh, ("P", 1))
V_v = fem.VectorFunctionSpace(mesh, ("P", 1))
V_t = fem.TensorFunctionSpace(mesh, ("P", 1))
print(mesh.geometry.dim, mesh.topology.dim)
```
yields error:
```bash
Non-matching cell of finite element and domain.
ERROR:UFL:Non-matching cell of finite element and domain.
Traceback (most recent call last):
  File "/root/shared/debug/mwe_gmsh.py", line 15, in <module>
    V_v = fem.VectorFunctionSpace(mesh, ("P", 1))
  File "/root/shared/dolfinx/python/dolfinx/fem/function.py", line 578, in VectorFunctionSpace
    return FunctionSpace(mesh, ufl_element)
  File "/root/shared/dolfinx/python/dolfinx/fem/function.py", line 452, in __init__
    super().__init__(mesh.ufl_domain(), element)
  File "/root/shared/ufl/ufl/functionspace.py", line 45, in __init__
    error("Non-matching cell of finite element and domain.")
  File "/root/shared/ufl/ufl/log.py", line 158, in error
    raise self._exception_type(self._format_raw(*message))
ufl.log.UFLException: Non-matching cell of finite element and domain.
```

**Comment by jpdean** [comment]
I suspect this issue might be fixed by https://github.com/FEniCS/dolfinx/pull/2386

**Comment by jorgensd** [comment]
This is not fixed yet. There are issues with the sub-spaces, i.e.
`V.sub(i)` does not work.

**Comment by jpdean** [comment]
Is the issue related to [this](https://github.com/FEniCS/basix/issues/603) by any chance? i.e. does specifying `dim=mesh.geometry.dim` when creating the vector function space fix the problem?

**Comment by mscroggs** [comment]
> Is the issue related to [this](https://github.com/FEniCS/basix/issues/603) by any chance? i.e. does specifying `dim=mesh.geometry.dim` when creating the vector function space fix the problem?

I've opened a PR in Basix to fix that and maybe fix this

**Comment by jorgensd** [comment]
@mscroggs  is this resolved?

**Comment by garth-wells** [comment]
@mscroggs, @jorgensd is this fixed now?

**Comment by mscroggs** [comment]
Is there a sensible test we can add to DOLFINx that will check that we don't break this in future?

**Comment by mscroggs** [comment]
This may have been fixed by https://github.com/FEniCS/basix/pull/617

**Comment by jorgensd** [comment]
> Is there a sensible test we can add to DOLFINx that will check that we don't break this in future?

Good question, maybe we need to solve a PDE on a manifold, or do something similar to what we do above.
I guess we could use locate_dofs_topological on a subspace to compare it to what one gets on the collapsed sub space.

**Comment by garth-wells** [comment]
> This may have been fixed by [FEniCS/basix#617](https://github.com/FEniCS/basix/pull/617)

Is this issue now fixed?
