### ISSUE TITLE
[BUG]: TensorFunctionSpace not working with symmetric mode

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#2534]
### How to reproduce the bug

Using `TensorFunctionSpace with `symmetry=True` does not work.
However, using `TensorElement` seem to work:
```python
from dolfinx.fem import FunctionSpace, form, TensorFunctionSpace
from dolfinx.mesh import create_unit_square
from mpi4py import MPI
from ufl import (TestFunction, TrialFunction,
                 dx,  inner, TensorElement)

msh = create_unit_square(MPI.COMM_WORLD, 10, 10)
el = TensorElement("Lagrange", msh.ufl_cell(), 1, symmetry=True)
V = FunctionSpace(msh, el)
sig = TrialFunction(V)
tau = TestFunction(V)
a = inner(sig, tau)*dx
af = form(a)
```

### Minimal Example (Python)

```Python
from dolfinx.fem import FunctionSpace, form, TensorFunctionSpace
from dolfinx.mesh import create_unit_square
from mpi4py import MPI
from ufl import (TestFunction, TrialFunction,
                 dx,  inner, TensorElement)
msh = create_unit_square(MPI.COMM_WORLD, 10, 10)
sym = True
V = TensorFunctionSpace(msh, ("Lagrange", 1), symmetry=True)
sig = TrialFunction(V)
tau = TestFunction(V)
a = inner(sig, tau)*dx
af = form(a)
```

### Output (Python)

```bash
Traceback (most recent call last):
  File "/root/shared/symmetric_mwe.py", line 19, in <module>
    af = form(a)
  File "/usr/local/dolfinx-real/lib/python3.10/dist-packages/dolfinx/fem/forms.py", line 178, in form
    return _create_form(form)
  File "/usr/local/dolfinx-real/lib/python3.10/dist-packages/dolfinx/fem/forms.py", line 173, in _create_form
    return _form(form)
  File "/usr/local/dolfinx-real/lib/python3.10/dist-packages/dolfinx/fem/forms.py", line 153, in _form
    ufcx_form, module, code = jit.ffcx_jit(mesh.comm, form,
  File "/usr/local/dolfinx-real/lib/python3.10/dist-packages/dolfinx/jit.py", line 56, in mpi_jit
    return local_jit(*args, **kwargs)
  File "/usr/local/dolfinx-real/lib/python3.10/dist-packages/dolfinx/jit.py", line 204, in ffcx_jit
    r = ffcx.codegeneration.jit.compile_forms([ufl_object], options=p_ffcx, **p_jit)
  File "/usr/local/lib/python3.10/dist-packages/ffcx/codegeneration/jit.py", line 199, in compile_forms
    raise e
  File "/usr/local/lib/python3.10/dist-packages/ffcx/codegeneration/jit.py", line 190, in compile_forms
    impl = _compile_objects(decl, forms, form_names, module_name, p, cache_dir,
  File "/usr/local/lib/python3.10/dist-packages/ffcx/codegeneration/jit.py", line 260, in _compile_objects
    _, code_body = ffcx.compiler.compile_ufl_objects(ufl_objects, prefix=module_name, options=options)
  File "/usr/local/lib/python3.10/dist-packages/ffcx/compiler.py", line 97, in compile_ufl_objects
    analysis = analyze_ufl_objects(ufl_objects, options)
  File "/usr/local/lib/python3.10/dist-packages/ffcx/analysis.py", line 86, in analyze_ufl_objects
    form_data = tuple(_analyze_form(form, options) for form in forms)
  File "/usr/local/lib/python3.10/dist-packages/ffcx/analysis.py", line 86, in <genexpr>
    form_data = tuple(_analyze_form(form, options) for form in forms)
  File "/usr/local/lib/python3.10/dist-packages/ffcx/analysis.py", line 164, in _analyze_form
    form_data = ufl.algorithms.compute_form_data(
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/compute_form_data.py", line 287, in compute_form_data
    form = apply_function_pullbacks(form)
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/apply_function_pullbacks.py", line 196, in apply_function_pullbacks
    return map_integrand_dags(FunctionPullbackApplier(), expr)
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/map_integrands.py", line 65, in map_integrand_dags
    return map_integrands(lambda expr: map_expr_dag(function, expr, compress),
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/map_integrands.py", line 28, in map_integrands
    mapped_integrals = [map_integrands(function, itg, only_integral_type)
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/map_integrands.py", line 28, in <listcomp>
    mapped_integrals = [map_integrands(function, itg, only_integral_type)
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/map_integrands.py", line 36, in map_integrands
    return itg.reconstruct(function(itg.integrand()))
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/map_integrands.py", line 65, in <lambda>
    return map_integrands(lambda expr: map_expr_dag(function, expr, compress),
  File "/usr/local/lib/python3.10/dist-packages/ufl/corealg/map_dag.py", line 36, in map_expr_dag
    result, = map_expr_dags(function, [expression], compress=compress,
  File "/usr/local/lib/python3.10/dist-packages/ufl/corealg/map_dag.py", line 97, in map_expr_dags
    r = handlers[v._ufl_typecode_](v)
  File "/usr/local/lib/python3.10/dist-packages/ufl/corealg/multifunction.py", line 31, in _memoized_handler
    r = handler(self, o)
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/apply_function_pullbacks.py", line 183, in form_argument
    f = apply_single_function_pullbacks(ReferenceValue(o), o.ufl_element())
  File "/usr/local/lib/python3.10/dist-packages/ufl/algorithms/apply_function_pullbacks.py", line 131, in apply_single_function_pullbacks
    raise ValueError(f"Expecting pulled back expression with shape '{element.value_shape()}', got '{f.ufl_shape}'")
ValueError: Expecting pulled back expression with shape '(2, 2)', got '(3,)'
```

### Version

main branch

### DOLFINx git commit

428293070cd1a2843257669b254678b20864de43

### Installation

Using the docker image `dolfinx/dolfinx:nightly`

### Additional information

First reported: https://fenicsproject.discourse.group/t/problems-with-symmetrical-tensor-spaces/10446

**Comment by mscroggs** [comment]
This might be fixes by https://github.com/FEniCS/basix/pull/647. Does anyone have an idea for a sensible test using symmetric tensor that we could add?

**Comment by mscroggs** [comment]
> Does anyone have an idea for a sensible test using symmetric tensor that we could add?

The static condensation demo uses symmetric tensors so can test this. Following https://github.com/FEniCS/dolfinx/pull/2381, that demo will use the Basix element directly
