### ISSUE TITLE
[BUG]: Installation with conda fails

### ISSUE THREAD

**Issue by Staudi14** [FEniCS/dolfinx#2580]
### How to reproduce the bug

I tried to install FeniCS under Linux via conda with the following commands:

```shell
conda create -n fenicsx-env
conda activate fenicsx-env
conda install -c conda-forge fenics-dolfinx mpich pyvista
```
After installation I could not load the python package.
Did I miss a step?

### Minimal Example (Python)

```Python
import dolfinx
```

### Output (Python)

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/staudi/.miniconda3/envs/fenicsx-env/lib/python3.10/site-packages/dolfinx/__init__.py", line 31, in <module>
    from dolfinx import fem, geometry, graph, io, jit, la, log, mesh, nls, plot
  File "/home/staudi/.miniconda3/envs/fenicsx-env/lib/python3.10/site-packages/dolfinx/fem/__init__.py", line 11, in <module>
    from dolfinx.fem import petsc
  File "/home/staudi/.miniconda3/envs/fenicsx-env/lib/python3.10/site-packages/dolfinx/fem/petsc.py", line 25, in <module>
    from dolfinx.fem import assemble
  File "/home/staudi/.miniconda3/envs/fenicsx-env/lib/python3.10/site-packages/dolfinx/fem/assemble.py", line 22, in <module>
    from dolfinx.fem.forms import FormMetaClass, form_types
  File "/home/staudi/.miniconda3/envs/fenicsx-env/lib/python3.10/site-packages/dolfinx/fem/forms.py", line 13, in <module>
    from dolfinx.fem.function import FunctionSpace
  File "/home/staudi/.miniconda3/envs/fenicsx-env/lib/python3.10/site-packages/dolfinx/fem/function.py", line 28, in <module>
    from dolfinx import jit, la
  File "/home/staudi/.miniconda3/envs/fenicsx-env/lib/python3.10/site-packages/dolfinx/jit.py", line 18, in <module>
    from mpi4py import MPI
  File "mpi4py/MPI/MPI.pyx", line 12, in init mpi4py.MPI
  File "mpi4py/MPI/atimport.pxi", line 215, in mpi4py.MPI.initialize
  File "mpi4py/MPI/mpierrhdl.pxi", line 7, in mpi4py.MPI.comm_set_eh
RuntimeError: 805918469
```

### Version

0.4.0

### Installation

```shell
conda create -n fenicsx-env
conda activate fenicsx-env
conda install -c conda-forge fenics-dolfinx mpich pyvista
```

### Additional information

[conda_install.log](https://github.com/FEniCS/dolfinx/files/10948151/conda_install.log)
[conda_list.log](https://github.com/FEniCS/dolfinx/files/10948153/conda_list.log)

**Comment by garth-wells** [comment]
Looks like an `mpi4py` error. Could you try importing `mpi4py`?

**Comment by Staudi14** [comment]
I tried `python -c "import mpi4py` and got no error message. The same with `python -c "from mpi4py import MPI"`.

**Comment by garth-wells** [comment]
Closing as conda/mpi4py bug. Best to raise an issue at https://github.com/conda-forge/mpi4py-feedstock.
