### ISSUE TITLE
[BUG]: AttributeError: module 'ufl.sobolevspace' has no attribute 'HInf'

### ISSUE THREAD

**Issue by asrvsn** [FEniCS/dolfinx#2599]
### How to reproduce the bug

After doing the `conda` installation on macOS (M1), Python 3.10:
```bash
mamba install -c conda-forge fenics-dolfinx fenics-libdolfinx
```
Importing `dolfinx` fails. 

### Minimal Example (Python)

```Python
import dolfinx
```

### Output (Python)

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/asrvsn/mambaforge/envs/volvox/lib/python3.10/site-packages/dolfinx/__init__.py", line 31, in <module>
    from dolfinx import fem, geometry, graph, io, jit, la, log, mesh, nls, plot
  File "/Users/asrvsn/mambaforge/envs/volvox/lib/python3.10/site-packages/dolfinx/fem/__init__.py", line 11, in <module>
    from dolfinx.fem import petsc
  File "/Users/asrvsn/mambaforge/envs/volvox/lib/python3.10/site-packages/dolfinx/fem/petsc.py", line 25, in <module>
    from dolfinx.fem import assemble
  File "/Users/asrvsn/mambaforge/envs/volvox/lib/python3.10/site-packages/dolfinx/fem/assemble.py", line 22, in <module>
    from dolfinx.fem.forms import FormMetaClass, form_types
  File "/Users/asrvsn/mambaforge/envs/volvox/lib/python3.10/site-packages/dolfinx/fem/forms.py", line 13, in <module>
    from dolfinx.fem.function import FunctionSpace
  File "/Users/asrvsn/mambaforge/envs/volvox/lib/python3.10/site-packages/dolfinx/fem/function.py", line 23, in <module>
    import basix.ufl_wrapper
  File "/Users/asrvsn/mambaforge/envs/volvox/lib/python3.10/site-packages/basix/ufl_wrapper.py", line 27, in <module>
    _basix.SobolevSpace.HInf: _ufl.sobolevspace.HInf,
AttributeError: module 'ufl.sobolevspace' has no attribute 'HInf'
```

### Version

0.6.0

**Comment by jhale** [comment]
I cannot reproduce this. Can you print `dolfinx.__version__` and `basix.__version__`?

**Comment by asrvsn** [comment]
Here's the result for `basix`:
```bash
>>> import basix
>>> basix.__version__
'0.6.0'
>>> from basix.ufl_wrapper import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/asrvsn/mambaforge/envs/volvox/lib/python3.10/site-packages/basix/ufl_wrapper.py", line 27, in <module>
    _basix.SobolevSpace.HInf: _ufl.sobolevspace.HInf,
AttributeError: module 'ufl.sobolevspace' has no attribute 'HInf'
>>> import dolfinx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/asrvsn/mambaforge/envs/volvox/lib/python3.10/site-packages/dolfinx/__init__.py", line 31, in <module>
    from dolfinx import fem, geometry, graph, io, jit, la, log, mesh, nls, plot
  File "/Users/asrvsn/mambaforge/envs/volvox/lib/python3.10/site-packages/dolfinx/fem/__init__.py", line 11, in <module>
    from dolfinx.fem import petsc
  File "/Users/asrvsn/mambaforge/envs/volvox/lib/python3.10/site-packages/dolfinx/fem/petsc.py", line 25, in <module>
    from dolfinx.fem import assemble
  File "/Users/asrvsn/mambaforge/envs/volvox/lib/python3.10/site-packages/dolfinx/fem/assemble.py", line 22, in <module>
    from dolfinx.fem.forms import FormMetaClass, form_types
  File "/Users/asrvsn/mambaforge/envs/volvox/lib/python3.10/site-packages/dolfinx/fem/forms.py", line 13, in <module>
    from dolfinx.fem.function import FunctionSpace
  File "/Users/asrvsn/mambaforge/envs/volvox/lib/python3.10/site-packages/dolfinx/fem/function.py", line 23, in <module>
    import basix.ufl_wrapper
  File "/Users/asrvsn/mambaforge/envs/volvox/lib/python3.10/site-packages/basix/ufl_wrapper.py", line 27, in <module>
    _basix.SobolevSpace.HInf: _ufl.sobolevspace.HInf,
AttributeError: module 'ufl.sobolevspace' has no attribute 'HInf'
```
Unfortunately I still run into the import issue for `dolfinx`, but `pip show fenics-dolfinx` yields:
```bash
% pip show fenics-dolfinx
Name: fenics-dolfinx
Version: 0.6.0
...
```

**Comment by asrvsn** [comment]
I've just created a fresh environment with Python 3.10.6 and re-installed, it's now working for me. I'm not sure what the issue was, perhaps there was a conflict with some other package.
