### ISSUE TITLE
[Installation Issue]: Fenicsx on apple silicon

### ISSUE THREAD

**Issue by ZeliangSu** [FEniCS/dolfinx#2812]
### How to reproduce the bug

Hi all,
I encountered the following issue after the installation from source. I'm using the Dolfinx on a Apple Silicon Machine. The C++ core installation was successful and other dependancies are installed smoothly without exceptions. Is any library missing ? Any help would be greatly appreciated!

### Minimal Example (Python)

```Python
import os
import numpy
import ufl
import dolfinx
from dolfinx import mesh, fem, io, plot
from dolfinx.fem.petsc import NonlinearProblem
from mpi4py import MPI
from petsc4py import PETSc
import pyvista as pv
 
# clears the terminal and prints dolfinx version
os.system('clear')
# prints dolfinx version
print(f"DOLFINx version: {dolfinx.__version__}")
 
# no of elements in each direction
NElem   = 8
 
# create a unit square with 8x8 elements with quad elements and use first order shape function
domain  = mesh.create_unit_square(MPI.COMM_WORLD,NElem,NElem,mesh.CellType.quadrilateral)
V       = fem.FunctionSpace(domain,("CG",1))
 
## define trial and test functions
u       = ufl.TrialFunction(V)
v       = ufl.TestFunction(V)
 
# source term of the poisson equation
f       = fem.Constant(domain, PETSc.ScalarType(-6))
 
## applying boundary conditions
uD      = fem.Function(V)
uD.interpolate(lambda x: 1 + x[0]**2 + 2 * x[1]**2)
tdim    = domain.topology.dim
fdim    = tdim-1
domain.topology.create_connectivity(fdim, tdim)
boundary_facets = mesh.exterior_facet_indices(domain.topology)
boundary_dofs   = fem.locate_dofs_topological(V, fdim, boundary_facets)
bc      = fem.dirichletbc(uD, boundary_dofs)
 
# bilinear form
a       = ufl.dot(ufl.grad(u), ufl.grad(v)) * ufl.dx
L       = f * v * ufl.dx
 
# set PETSc solver options
sol_opts = {"ksp_type": "preonly", "pc_type": "lu"}
# formulate the problem
problem = fem.petsc.LinearProblem(a, L, bcs=[bc], petsc_options=sol_opts)
# solve the problem
uh = problem.solve()
```

### Output (Python)

```bash
DOLFINx version: 0.7.0
TERM environment variable not set.
In file included from libffcx_forms_e904ad0cf291329b43d1c41300b6ad20504ac108.c:57:
/opt/anaconda3/envs/fenicsx/include/python3.11/Python.h:23:12: fatal error: 'stdlib.h' file not found
#  include <stdlib.h>
           ^~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 185, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/opt/anaconda3/envs/fenicsx/bin/clang' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/cffi/ffiplatform.py", line 48, in _build
    dist.run_command('build_ext')
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 88, in run
    _build_ext.run(self)
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
    _build_ext.build_extension(self, ext)
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 600, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/setuptools/_distutils/unixccompiler.py", line 187, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command '/opt/anaconda3/envs/fenicsx/bin/clang' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "poisson.py", line 49, in <module>
    problem = fem.petsc.LinearProblem(a, L, bcs=[bc], petsc_options=sol_opts)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/dolfinx/fem/petsc.py", line 588, in __init__
    self._a = _create_form(a, form_compiler_options=form_compiler_options, jit_options=jit_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/dolfinx/fem/forms.py", line 188, in form
    return _create_form(form)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/dolfinx/fem/forms.py", line 183, in _create_form
    return _form(form)
           ^^^^^^^^^^^
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/dolfinx/fem/forms.py", line 141, in _form
    ufcx_form, module, code = jit.ffcx_jit(mesh.comm, form,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/dolfinx/jit.py", line 56, in mpi_jit
    return local_jit(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/dolfinx/jit.py", line 204, in ffcx_jit
    r = ffcx.codegeneration.jit.compile_forms([ufl_object], options=p_ffcx, **p_jit)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/ffcx/codegeneration/jit.py", line 199, in compile_forms
    raise e
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/ffcx/codegeneration/jit.py", line 190, in compile_forms
    impl = _compile_objects(decl, forms, form_names, module_name, p, cache_dir,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/ffcx/codegeneration/jit.py", line 284, in _compile_objects
    ffibuilder.compile(tmpdir=cache_dir, verbose=True, debug=cffi_debug)
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/cffi/api.py", line 725, in compile
    return recompile(self, module_name, source, tmpdir=tmpdir,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/cffi/recompiler.py", line 1564, in recompile
    outputfilename = ffiplatform.compile('.', ext,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/cffi/ffiplatform.py", line 54, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command '/opt/anaconda3/envs/fenicsx/bin/clang' failed with exit code 1
Exception ignored in: <function LinearProblem.__del__ at 0x12879d800>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/fenicsx/lib/python3.11/site-packages/dolfinx/fem/petsc.py", line 627, in __del__
    self._solver.destroy()
    ^^^^^^^^^^^^
AttributeError: 'LinearProblem' object has no attribute '_solver'
```
```


### Version

main branch

### DOLFINx git commit

_No response_

### Installation

Dolfinx 0.7.0

### Additional information

The c++ is following:

> Apple clang version 14.0.3 (clang-1403.0.22.14.1)
> Target: arm64-apple-darwin22.6.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by francesco-ballarin** [comment]
I believe that the relevant error is 
```
/opt/anaconda3/envs/fenicsx/include/python3.11/Python.h:23:12: fatal error: 'stdlib.h' file not found
```

Can you compile a simple hello world c++ program with the c++ compiler that comes in the conda environment?

**Comment by francesco-ballarin** [comment]
After a week, we have not received further feedback. Therefore, I am going ahead and closing this. If this is still an issue for you, please post it in the discourse forum.
