### ISSUE TITLE
[BUG]: Strange Error When Solving Navier-Stokes Equation Using Taylor-Hood elements

### ISSUE THREAD

**Issue by bladesaber** [FEniCS/dolfinx#2961]
### Summarize the issue

Hi, there is no error happen when solving the Stokes Equation. And throwing msg "LinearProblem object has no attribute _solver" when solving the Navier-Stokes Equation. It seems like the ufl operator on "inner(dot(u, grad(u)), v)" will cause the problem. 

Thanks, everyone. Best regard.

### How to reproduce the bug

Please run the code provided below.

### Minimal Example (Python)

```Python
import numpy as np
import ufl
from mpi4py import MPI
import dolfinx
from dolfinx.fem.petsc import LinearProblem
from ufl import inner, grad, div, dot
from basix.ufl import element, mixed_element

domain = dolfinx.mesh.create_rectangle(MPI.COMM_WORLD, [np.array([0, 0]), np.array([1, 1])], [32, 32])
tdim = domain.topology.dim
fdim = tdim - 1


def noslip_boundary(x):
    # Function to mark x = 0, x = 1 and y = 0
    return np.logical_or(
        np.logical_or(np.isclose(x[0], 0.0), np.isclose(x[0], 1.0)),
        np.isclose(x[1], 0.0)
    )


def lid(x):
    # Function to mark the lid (y = 1)
    return np.isclose(x[1], 1.0)


def lid_velocity_expression(x):
    # Lid velocity
    return np.stack((np.ones(x.shape[1]), np.zeros(x.shape[1])))


P2 = element("Lagrange", domain.basix_cell(), 2, shape=(domain.geometry.dim,))
P1 = element("Lagrange", domain.basix_cell(), 1)
TH = mixed_element([P2, P1])
W = dolfinx.fem.functionspace(domain, TH)

W0, W1 = W.sub(0), W.sub(1)
V, V_to_W = W0.collapse()
Q, Q_to_W = W1.collapse()

noslip = dolfinx.fem.Function(V)
facets = dolfinx.mesh.locate_entities_boundary(domain, fdim, noslip_boundary)
dofs = dolfinx.fem.locate_dofs_topological((W0, V), fdim, facets)
bc0 = dolfinx.fem.dirichletbc(noslip, dofs, W0)

# Driving velocity condition u = (1, 0) on top boundary (y = 1)
lid_velocity = dolfinx.fem.Function(V)
lid_velocity.interpolate(lid_velocity_expression)
facets = dolfinx.mesh.locate_entities_boundary(domain, fdim, lid)
dofs = dolfinx.fem.locate_dofs_topological((W0, V), fdim, facets)
bc1 = dolfinx.fem.dirichletbc(lid_velocity, dofs, W0)

# Collect Dirichlet boundary conditions
bcs = [bc0, bc1]

# Define variational problem
(u, p) = ufl.TrialFunctions(W)
(v, q) = ufl.TestFunctions(W)
f = dolfinx.fem.Function(V)

nu = 1. / 400.
# ------ Stokes Equation, No error
# F_form = nu * inner(grad(u), grad(v)) * ufl.dx - p * div(v) * ufl.dx + div(u) * q * ufl.dx - inner(f, v) * ufl.dx
# ------ Navier-Stokes Equation, error happen
F_form = (inner(dot(u, grad(u)), v) + nu * inner(grad(u), grad(v)) - p * div(v) + q * div(u)) * ufl.dx - inner(f, v) * ufl.dx

a_form: ufl.form.Form = ufl.lhs(F_form)
L_form: ufl.form.Form = ufl.rhs(F_form)

uh = LinearProblem(a_form, L_form, [bc0, bc1])
```

### Output (Python)

```bash
hwloc/linux: Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
Traceback (most recent call last):
  File "/home/admin123456/Desktop/work/MAPF_Pipeline/test2.py", line 71, in <module>
    uh = LinearProblem(a_form, L_form, [bc0, bc1])
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/dolfinx/fem/petsc.py", line 588, in __init__
    self._a = _create_form(a, form_compiler_options=form_compiler_options, jit_options=jit_options)
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/dolfinx/fem/forms.py", line 188, in form
    return _create_form(form)
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/dolfinx/fem/forms.py", line 183, in _create_form
    return _form(form)
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/dolfinx/fem/forms.py", line 141, in _form
    ufcx_form, module, code = jit.ffcx_jit(mesh.comm, form,
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/dolfinx/jit.py", line 56, in mpi_jit
    return local_jit(*args, **kwargs)
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/dolfinx/jit.py", line 204, in ffcx_jit
    r = ffcx.codegeneration.jit.compile_forms([ufl_object], options=p_ffcx, **p_jit)
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/ffcx/codegeneration/jit.py", line 199, in compile_forms
    raise e
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/ffcx/codegeneration/jit.py", line 190, in compile_forms
    impl = _compile_objects(decl, forms, form_names, module_name, p, cache_dir,
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/ffcx/codegeneration/jit.py", line 260, in _compile_objects
    _, code_body = ffcx.compiler.compile_ufl_objects(ufl_objects, prefix=module_name, options=options)
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/ffcx/compiler.py", line 97, in compile_ufl_objects
    analysis = analyze_ufl_objects(ufl_objects, options)
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/ffcx/analysis.py", line 88, in analyze_ufl_objects
    form_data = tuple(_analyze_form(form, options) for form in forms)
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/ffcx/analysis.py", line 88, in <genexpr>
    form_data = tuple(_analyze_form(form, options) for form in forms)
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/ffcx/analysis.py", line 163, in _analyze_form
    form_data = ufl.algorithms.compute_form_data(
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/ufl/algorithms/compute_form_data.py", line 415, in compute_form_data
    check_form_arity(preprocessed_form, self.original_form.arguments(), complex_mode)
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/ufl/algorithms/check_arities.py", line 198, in check_form_arity
    check_integrand_arity(itg.integrand(), arguments, complex_mode)
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/ufl/algorithms/check_arities.py", line 179, in check_integrand_arity
    arg_tuples = map_expr_dag(rules, expr, compress=False)
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/ufl/corealg/map_dag.py", line 34, in map_expr_dag
    result, = map_expr_dags(function, [expression], compress=compress,
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/ufl/corealg/map_dag.py", line 100, in map_expr_dags
    r = handlers[v._ufl_typecode_](v, *[vcache[u] for u in v.ufl_operands])
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/ufl/algorithms/check_arities.py", line 71, in product
    f"{x[0].number()}, argument is {_afmt(x)}.")
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/ufl/algorithms/check_arities.py", line 17, in _afmt
    return tuple(f"conj({arg})" if conj else str(arg) for arg, conj in atuple)
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/ufl/algorithms/check_arities.py", line 17, in <genexpr>
    return tuple(f"conj({arg})" if conj else str(arg) for arg, conj in atuple)
ValueError: too many values to unpack (expected 2)
Exception ignored in: <function LinearProblem.__del__ at 0x7fbb542cf040>
Traceback (most recent call last):
  File "/home/admin123456/anaconda3/envs/py39-env/lib/python3.9/site-packages/dolfinx/fem/petsc.py", line 627, in __del__
    self._solver.destroy()
AttributeError: 'LinearProblem' object has no attribute '_solver'
```

### Version

0.7.1

### DOLFINx git commit

5581bae61212a1fc936824cdd571776188532a96

### Installation

conda install -c conda-forge fenics-dolfinx mpich pyvista

**Comment by francesco-ballarin** [comment]
Your problem isn't linear
```
F_form = (inner(dot(u, grad(u)), v)  + ...
```
so you can't expect `LinearProblem` to solve it.

Post future questions like this at https://fenicsproject.discourse.group/

**Comment by jorgensd** [comment]
`F_form = (inner(dot(u, grad(u)), v) + nu * inner(grad(u), grad(v)) - p * div(v) + q * div(u)) * ufl.dx - inner(f, v) * ufl.dx`
is not a linear form.
It is non-linear, and therefore you need to use the `NonLinearProblem` and `NewtonSolver` (see: https://docs.fenicsproject.org/dolfinx/v0.7.3/python/demos/demo_cahn-hilliard.html), or implement a custom non-linear solver such as: https://jsdokken.com/dolfinx-tutorial/chapter4/newton-solver.html
t
